// frontend-react/app/register/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Eye, EyeOff, Loader2 } from "lucide-react";
import { isAxiosError } from "axios";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { useRegister, redirectToGithub } from "@/hooks/useAuth";

const registerSchema = z
  .object({
    username: z
      .string()
      .min(3, "用户名至少3个字符")
      .max(50, "用户名最多50个字符"),
    email: z.email("请输入有效的邮箱地址"),
    password: z.string().min(6, "密码至少6位").max(100, "密码最多100位"),
    confirmPassword: z.string().min(1, "请确认密码"),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: "两次输入的密码不一致",
    path: ["confirmPassword"],
  });

type RegisterFormValues = z.infer<typeof registerSchema>;

const AVAILABLE_TAGS = [
  "油画",
  "水彩",
  "素描",
  "雕塑",
  "摄影",
  "数字艺术",
  "抽象",
  "写实",
  "现代",
  "古典",
];

function getErrorMessage(error: unknown) {
  if (!error) {
    return "";
  }

  if (isAxiosError<{ message?: string }>(error)) {
    return error.response?.data?.message ?? "注册失败，请重试";
  }

  return "注册失败，请重试";
}

function isSafeRedirect(url: string | null): url is string {
  return !!url && url.startsWith("/") && !url.startsWith("//");
}

export default function RegisterPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const registerMutation = useRegister();
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [selectedTags, setSelectedTags] = useState<string[]>([]);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterFormValues>({
    resolver: zodResolver(registerSchema),
    defaultValues: {
      username: "",
      email: "",
      password: "",
      confirmPassword: "",
    },
  });

  const toggleTag = (tag: string) => {
    setSelectedTags((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag],
    );
  };

  const onSubmit = (values: RegisterFormValues) => {
    registerMutation.mutate(
      {
        username: values.username,
        email: values.email,
        password: values.password,
        tags: selectedTags,
      },
      {
        onSuccess: () => {
          const redirect = searchParams.get("redirect");
          router.replace(isSafeRedirect(redirect) ? redirect : "/home");
        },
      },
    );
  };

  const errorMessage = getErrorMessage(registerMutation.error);

  return (
    <div className="relative flex min-h-screen justify-center px-4 py-8">
      <div
        className="absolute inset-0 bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: "url('/login-bg.jpg')" }}
      />

      <Card className="relative z-10 my-auto w-full max-w-md rounded-2xl border border-white/40 bg-white/80 shadow-2xl backdrop-blur-xl animate-in fade-in zoom-in duration-500 transition-transform hover:-translate-y-1">
        <CardHeader className="items-center text-center">
          <CardTitle className="text-2xl font-bold text-indigo-600">
            注册
          </CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="username">用户名</Label>
              <Input
                id="username"
                placeholder="请输入用户名（3-50个字符）"
                className="focus-visible:!border-indigo-400 focus-visible:!ring-indigo-400/30"
                {...register("username")}
              />
              {errors.username && (
                <p className="text-sm text-destructive">
                  {errors.username.message}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="email">邮箱</Label>
              <Input
                id="email"
                type="email"
                placeholder="请输入邮箱"
                className="focus-visible:!border-indigo-400 focus-visible:!ring-indigo-400/30"
                {...register("email")}
              />
              {errors.email && (
                <p className="text-sm text-destructive">
                  {errors.email.message}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">密码</Label>
              <div className="relative">
                <Input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  placeholder="请输入密码（至少6位）"
                  className="pr-10 focus-visible:!border-indigo-400 focus-visible:!ring-indigo-400/30"
                  {...register("password")}
                />
                <button
                  type="button"
                  tabIndex={-1}
                  onClick={() => setShowPassword((v) => !v)}
                  className="absolute inset-y-0 right-3 flex items-center text-muted-foreground hover:text-foreground"
                >
                  {showPassword ? (
                    <EyeOff className="size-4" />
                  ) : (
                    <Eye className="size-4" />
                  )}
                </button>
              </div>
              {errors.password && (
                <p className="text-sm text-destructive">
                  {errors.password.message}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="confirmPassword">确认密码</Label>
              <div className="relative">
                <Input
                  id="confirmPassword"
                  type={showConfirmPassword ? "text" : "password"}
                  placeholder="请再次输入密码"
                  className="pr-10 focus-visible:!border-indigo-400 focus-visible:!ring-indigo-400/30"
                  {...register("confirmPassword")}
                />
                <button
                  type="button"
                  tabIndex={-1}
                  onClick={() => setShowConfirmPassword((v) => !v)}
                  className="absolute inset-y-0 right-3 flex items-center text-muted-foreground hover:text-foreground"
                >
                  {showConfirmPassword ? (
                    <EyeOff className="size-4" />
                  ) : (
                    <Eye className="size-4" />
                  )}
                </button>
              </div>
              {errors.confirmPassword && (
                <p className="text-sm text-destructive">
                  {errors.confirmPassword.message}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label>兴趣标签（可选）</Label>
              <div className="flex flex-wrap gap-2">
                {AVAILABLE_TAGS.map((tag) => {
                  const selected = selectedTags.includes(tag);
                  return (
                    <button
                      key={tag}
                      type="button"
                      onClick={() => toggleTag(tag)}
                      className={
                        selected
                          ? "rounded-full bg-indigo-500 px-3 py-1 text-xs text-white"
                          : "rounded-full border border-border bg-background px-3 py-1 text-xs text-muted-foreground transition-colors hover:border-indigo-400 hover:text-indigo-600"
                      }
                    >
                      {tag}
                    </button>
                  );
                })}
              </div>
            </div>

            {errorMessage && (
              <Alert
                variant="destructive"
                className="animate-in fade-in slide-in-from-top-1"
              >
                <AlertDescription>{errorMessage}</AlertDescription>
              </Alert>
            )}

            <Button
              type="submit"
              className="w-full bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-lg shadow-indigo-500/30 hover:from-indigo-600 hover:to-purple-700 hover:shadow-indigo-500/40 hover:-translate-y-0.5"
              disabled={registerMutation.isPending}
            >
              {registerMutation.isPending && (
                <Loader2 className="mr-2 animate-spin" />
              )}
              注册
            </Button>
          </form>

          <div className="flex items-center gap-4">
            <Separator className="flex-1" />
            <span className="text-xs text-muted-foreground">
              使用第三方账号注册
            </span>
            <Separator className="flex-1" />
          </div>

          <div className="flex gap-3">
            <Button
              type="button"
              variant="outline"
              className="flex-1 hover:-translate-y-0.5 hover:border-foreground hover:bg-foreground hover:text-background"
              onClick={redirectToGithub}
            >
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12" />
              </svg>
              GitHub
            </Button>
            <Button type="button" variant="outline" className="flex-1" disabled>
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path d="M8.691 2.188C3.891 2.188 0 5.476 0 9.53c0 2.212 1.17 4.203 3.002 5.55a.59.59 0 0 1 .213.665l-.39 1.48c-.019.07-.048.141-.048.213c0 .163.13.295.29.295a.33.33 0 0 0 .167-.054l1.903-1.114a.86.86 0 0 1 .717-.098a10.2 10.2 0 0 0 2.837.403c.276 0 .543-.027.811-.05c-.857-2.578.157-4.972 1.932-6.446c1.703-1.415 3.882-1.98 5.853-1.838c-.576-3.583-4.196-6.348-8.596-6.348M5.785 5.991c.642 0 1.162.529 1.162 1.18a1.17 1.17 0 0 1-1.162 1.178A1.17 1.17 0 0 1 4.623 7.17c0-.651.52-1.18 1.162-1.18zm5.813 0c.642 0 1.162.529 1.162 1.18a1.17 1.17 0 0 1-1.162 1.178a1.17 1.17 0 0 1-1.162-1.178c0-.651.52-1.18 1.162-1.18m5.34 2.867c-1.797-.052-3.746.512-5.28 1.786c-1.72 1.428-2.687 3.72-1.78 6.22c.942 2.453 3.666 4.229 6.884 4.229c.826 0 1.622-.12 2.361-.336a.72.72 0 0 1 .598.082l1.584.926a.3.3 0 0 0 .14.047c.134 0 .24-.111.24-.247c0-.06-.023-.12-.038-.177l-.327-1.233a.6.6 0 0 1-.023-.156a.49.49 0 0 1 .201-.398C23.024 18.48 24 16.82 24 14.98c0-3.21-2.931-5.837-6.656-6.088V8.89c-.135-.01-.27-.027-.407-.03zm-2.53 3.274c.535 0 .969.44.969.982a.976.976 0 0 1-.969.983a.976.976 0 0 1-.969-.983c0-.542.434-.982.97-.982zm4.844 0c.535 0 .969.44.969.982a.976.976 0 0 1-.969.983a.976.976 0 0 1-.969-.983c0-.542.434-.982.969-.982" />
              </svg>
              微信
            </Button>
          </div>

          <p className="text-center text-sm text-muted-foreground">
            已有账号？
            <Link
              href="/login"
              className="ml-1 font-medium text-indigo-600 underline-offset-4 transition-colors hover:text-purple-600 hover:underline"
            >
              立即登录
            </Link>
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

// frontend/src/views/auth/Register.vue
<template>
  <div class="register-page">
    <el-container>
      <el-main>
        <div class="register-container">
          <el-card class="register-card" shadow="always">
            <h2 class="register-title">注册</h2>
            
            <el-form @submit.prevent="handleRegister" :model="form" label-position="top">
              <el-form-item label="用户名">
                <el-input
                  v-model="form.username"
                  placeholder="请输入用户名"
                  required
                />
              </el-form-item>

              <el-form-item label="邮箱">
                <el-input
                  v-model="form.email"
                  type="email"
                  placeholder="请输入邮箱"
                  required
                />
              </el-form-item>

              <el-form-item label="密码">
                <el-input
                  v-model="form.password"
                  type="password"
                  placeholder="请输入密码（至少6位）"
                  required
                  minlength="6"
                  show-password
                />
              </el-form-item>

              <el-form-item label="确认密码">
                <el-input
                  v-model="form.confirmPassword"
                  type="password"
                  placeholder="请再次输入密码"
                  required
                  show-password
                />
              </el-form-item>

              <el-form-item label="头像（可选）">
                <el-upload
                  class="avatar-uploader"
                  :show-file-list="false"
                  :on-change="handleAvatarChange"
                  accept="image/*"
                  :auto-upload="false"
                >
                  <img v-if="avatarPreview" :src="avatarPreview" class="avatar-preview" />
                  <el-icon v-else class="avatar-uploader-icon"><Plus /></el-icon>
                </el-upload>
              </el-form-item>

              <el-form-item label="兴趣标签（可选）">
                <div class="tags-container">
                  <el-tag
                    v-for="tag in availableTags"
                    :key="tag"
                    :type="form.tags.includes(tag) ? 'primary' : 'info'"
                    class="tag-item"
                    @click="toggleTag(tag)"
                    style="cursor: pointer;"
                  >
                    {{ tag }}
                  </el-tag>
                </div>
              </el-form-item>

              <el-form-item>
                <el-button
                  type="primary"
                  class="w-100"
                  :loading="loading"
                  :disabled="form.password !== form.confirmPassword"
                  @click="handleRegister"
                >
                  注册
                </el-button>
              </el-form-item>
            </el-form>

            <div class="login-link">
              已有账号？
              <router-link to="/login">立即登录</router-link>
            </div>

            <el-alert
              v-if="error"
              type="error"
              :title="error"
              :closable="false"
              class="mt-3"
            />
          </el-card>
        </div>
      </el-main>
    </el-container>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
import userApi from '@/api/user'
import { isAxiosError } from 'axios'
import type { RegisterRequest } from '@/types'

// 本地表单类型，tags 设为必选以解决模板类型错误
interface RegisterForm extends Omit<RegisterRequest, 'tags'> {
  tags: string[]
  confirmPassword: string
  avatar: File | null
}

const router = useRouter()
const userStore = useUserStore()

const form = ref<RegisterForm>({
  username: '',
  email: '',
  password: '',
  confirmPassword: '',
  tags: [],
  avatar: null
})

const availableTags = ['油画', '水彩', '素描', '雕塑', '摄影', '数字艺术', '抽象', '写实', '现代', '古典']
const avatarPreview = ref('')
const loading = ref(false)
const error = ref('')

const handleAvatarChange = (event: Event) => {
  const target = event.target as HTMLInputElement | null
  const file = target?.files?.[0]
  if (file) {
    form.value.avatar = file
    const reader = new FileReader()
    reader.onload = (e) => {
      avatarPreview.value = e.target?.result as string
    }
    reader.readAsDataURL(file)
  }
}

const toggleTag = (tag: string) => {
  const index = form.value.tags.indexOf(tag)
  if (index > -1) {
    form.value.tags.splice(index, 1)
  } else {
    form.value.tags.push(tag)
  }
}

const handleRegister = async () => {
  if (form.value.password !== form.value.confirmPassword) {
    error.value = '两次输入的密码不一致'
    return
  }

  loading.value = true
  error.value = ''
  
  try {
    const userData = {
      username: form.value.username,
      email: form.value.email,
      password: form.value.password,
      tags: form.value.tags
    }

    await userStore.register(userData)

    // 如果有头像，先上传头像获取 URL
    if (form.value.avatar) {
      const avatarResponse = await userApi.uploadAvatar(form.value.avatar)
      await userStore.updateUserInfo({ avatar: avatarResponse.url })
    }

    router.push('/home')
  } catch (err: unknown) {
    if (isAxiosError<{ message?: string }>(err)) {
      error.value = err.response?.data?.message ?? '注册失败，请重试'
    } else {
      error.value = '注册失败，请重试'
    }
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.register-page {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  min-height: 100vh;
}

.register-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  padding: 20px;
}

.register-card {
  width: 100%;
  max-width: 500px;
  border-radius: 15px;
}

.register-title {
  text-align: center;
  margin-bottom: 24px;
}

.avatar-uploader {
  text-align: center;
}

.avatar-preview {
  width: 100px;
  height: 100px;
  border-radius: 50%;
  object-fit: cover;
  display: block;
  margin: 0 auto;
}

.avatar-uploader-icon {
  font-size: 28px;
  color: #8c939d;
  width: 100px;
  height: 100px;
  line-height: 100px;
  text-align: center;
  border: 1px dashed #d9d9d9;
  border-radius: 50%;
  cursor: pointer;
}

.tags-container {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.tag-item {
  margin: 0;
}

.login-link {
  text-align: center;
}

.w-100 {
  width: 100%;
}

.mt-3 {
  margin-top: 12px;
}
</style>
